# Generated by Django 4.0.3 on 2022-03-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_activity_list',
        ),
    ]
