# Generated by Django 4.0.3 on 2022-03-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_rename_originizer_id_activity_organizer_id'),
        ('activity_comment', '0002_delete_comment_activity_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_comment',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
    ]
