# Generated by Django 4.0.3 on 2022-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_calendar',
            name='user_id',
        ),
    ]
