# Generated by Django 4.0.3 on 2022-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_calendar', '0002_remove_public_calendar_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_calendar',
            name='activity_title',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
