# Generated by Django 4.0.3 on 2022-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_calendar', '0004_remove_public_calendar_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_calendar',
            name='activity_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='public_calendar',
            name='activity_start_date',
            field=models.DateTimeField(),
        ),
    ]
