# Generated by Django 4.0.3 on 2022-04-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_calendar', '0006_public_calendar_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_calendar',
            old_name='is_detele',
            new_name='is_delete',
        ),
    ]
