# Generated by Django 4.0.3 on 2022-04-17 01:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_post_content_alter_post_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(max_length=1024),
        ),
    ]
