# Generated by Django 4.0.3 on 2022-03-26 15:05

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='user/default.png', upload_to=user.models.user_dictory),
        ),
    ]
