# Generated by Django 4.0.3 on 2022-03-31 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_check_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Verification Code')),
                ('email', models.EmailField(max_length=50, verbose_name='User Email')),
                ('send_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Send Time')),
                ('exprie_time', models.DateTimeField(null=True)),
                ('email_type', models.CharField(choices=[('register', 'Registration'), ('forget', 'Retrieve Password')], max_length=10)),
            ],
        ),
    ]
