# Generated by Django 4.0.3 on 2022-03-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_email_check_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='usr', max_length=256),
        ),
    ]
