# Generated by Django 4.0.3 on 2022-04-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_email_check_old'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_check_old',
        ),
    ]
