# Generated by Django 4.0.3 on 2022-04-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_email_check_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_orginazation',
            new_name='is_organization',
        ),
    ]
