# Generated by Django 4.0.3 on 2022-04-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_is_orginazation_user_is_organization'),
        ('user', '0010_alter_user_id'),
    ]

    operations = [
    ]
