# Generated by Django 4.0.3 on 2022-04-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_check_new',
            old_name='exprie_time',
            new_name='expire_time',
        ),
    ]
