# Generated by Django 4.0.3 on 2022-03-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_calendar', '0002_private_calendar_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_calendar',
            name='activity_date',
        ),
        migrations.AddField(
            model_name='private_calendar',
            name='activity_end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='private_calendar',
            name='activity_start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
