# Generated by Django 4.0.3 on 2022-04-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_email_check_old'),
        ('private_calendar', '0004_alter_private_calendar_activity_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_calendar',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.user'),
        ),
    ]
