# Generated by Django 4.0.3 on 2022-03-27 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('post_comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post.post'),
        ),
        migrations.DeleteModel(
            name='Comment_post_list',
        ),
    ]
