# Generated by Django 4.0.3 on 2022-04-17 00:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_comment', '0003_alter_post_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
