# Generated by Django 4.0.3 on 2022-04-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_comment', '0004_alter_post_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='content',
            field=models.CharField(max_length=1024),
        ),
    ]
