# Generated by Django 4.0.3 on 2022-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participant_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='participant_num',
            field=models.IntegerField(default=0),
        ),
    ]
