# Generated by Django 4.0.3 on 2022-03-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_is_delete_activity_is_outdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_outdata',
            new_name='is_outdate',
        ),
    ]
