# Generated by Django 4.0.3 on 2022-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_is_outdata_activity_is_outdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
