# Generated by Django 4.0.3 on 2022-03-27 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participant_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
