# Generated by Django 4.0.3 on 2022-03-27 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_max_participant_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='part_max_num',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
