# Generated by Django 4.0.3 on 2022-03-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activity_originizer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='originizer_id',
            new_name='organizer_id',
        ),
    ]
