# Generated by Django 4.0.3 on 2022-03-27 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_rename_originizer_id_activity_organizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score_avg',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='score_num',
            field=models.IntegerField(default=0),
        ),
    ]
