# Generated by Django 4.0.3 on 2022-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activity_cover_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
